// Code generated by goyacc -o parser.go sql.y. DO NOT EDIT.

//line sql.y:4
package vmsql

import (
	__yyfmt__ "fmt"
	"reflect"
	"strings"
)

//line sql.y:4
func setParseTree(yylex yyLexer, stmt Statement) {
	yylex.(*Tokenizer).ParseTree = stmt
}

func setDDL(yylex yyLexer, node Statement) {
	yylex.(*Tokenizer).partialDDL = node
}

func incNesting(yylex yyLexer) bool {
	yylex.(*Tokenizer).nesting++
	if yylex.(*Tokenizer).nesting == 200 {
		return true
	}
	return false
}

func decNesting(yylex yyLexer) {
	yylex.(*Tokenizer).nesting--
}

// skipToEnd forces the lexer to end prematurely. Not all SQL statements
// are supported by the Parser, thus calling skipToEnd will make the lexer
// return EOF early.
func skipToEnd(yylex yyLexer) {
	yylex.(*Tokenizer).SkipToEnd = true
}

func bindVariable(yylex yyLexer, bvar string) {
	yylex.(*Tokenizer).BindVars[bvar] = struct{}{}
}

//line sql.y:37
type yySymType struct {
	yys           int
	columns       []*Column
	str           string
	statement     Statement
	column        *Column
	columnType    reflect.Kind
	tuples        [][]string
	tuple         []string
	tagFilter     *TagFilter
	deleteFilters *DeleteFilter
	functions     [][]*Function
	function      []*Function
	orderBy       *OrderBy
	whereFilters  *MultiFilters
	timeFilter    *TimeFilter
	otherFilter   *OtherFilter
}

const LEX_ERROR = 57346
const UNUSED = 57347
const OR = 57348
const XOR = 57349
const AND = 57350
const NOT = 57351
const BETWEEN = 57352
const CASE = 57353
const WHEN = 57354
const THEN = 57355
const ELSE = 57356
const END = 57357
const LE = 57358
const GE = 57359
const NE = 57360
const NULL_SAFE_EQUAL = 57361
const IS = 57362
const LIKE = 57363
const REGEXP = 57364
const IN = 57365
const SHIFT_LEFT = 57366
const SHIFT_RIGHT = 57367
const DIV = 57368
const MOD = 57369
const UNARY = 57370
const CREATE = 57371
const INSERT = 57372
const INTO = 57373
const VALUES = 57374
const DELETE = 57375
const DROP = 57376
const FROM = 57377
const WHERE = 57378
const SELECT = 57379
const LIMIT = 57380
const ORDER = 57381
const BY = 57382
const GROUP = 57383
const DESC = 57384
const ASC = 57385
const DESCRIBE = 57386
const BOOL = 57387
const STRING = 57388
const INT32 = 57389
const UINT32 = 57390
const INT64 = 57391
const UINT64 = 57392
const FLOAT = 57393
const DOUBLE = 57394
const BOOLEAN = 57395
const BIT = 57396
const TINYINT = 57397
const SMALLINT = 57398
const INT = 57399
const INTEGER = 57400
const BIGINT = 57401
const STRING_NUM = 57402
const INTEGER_NUM = 57403
const FLOAT_NUM = 57404
const DECIMAL_NUM = 57405
const TRUE_NUM = 57406
const FALSE_NUM = 57407
const ID = 57408
const AT_ID = 57409
const AT_AT_ID = 57410
const HEX = 57411
const INTEGRAL = 57412
const DECIMAL = 57413
const HEXNUM = 57414
const BIT_LITERAL = 57415
const UTINYINT = 57416
const USMALLINT = 57417
const UINT = 57418
const UBIGINT = 57419
const REAL = 57420
const IF = 57421
const EXISTS = 57422
const NULL = 57423
const DEFAULT = 57424
const TAG = 57425
const VALUE = 57426
const DATABASE = 57427
const TABLE = 57428

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"UNUSED",
	"'('",
	"','",
	"')'",
	"OR",
	"'|'",
	"XOR",
	"AND",
	"NOT",
	"'!'",
	"BETWEEN",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"'='",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"NE",
	"NULL_SAFE_EQUAL",
	"IS",
	"LIKE",
	"REGEXP",
	"IN",
	"'&'",
	"SHIFT_LEFT",
	"SHIFT_RIGHT",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"DIV",
	"'%'",
	"MOD",
	"'^'",
	"'~'",
	"UNARY",
	"CREATE",
	"INSERT",
	"INTO",
	"VALUES",
	"DELETE",
	"DROP",
	"FROM",
	"WHERE",
	"SELECT",
	"LIMIT",
	"ORDER",
	"BY",
	"GROUP",
	"DESC",
	"ASC",
	"':'",
	"'['",
	"']'",
	"DESCRIBE",
	"BOOL",
	"STRING",
	"INT32",
	"UINT32",
	"INT64",
	"UINT64",
	"FLOAT",
	"DOUBLE",
	"BOOLEAN",
	"BIT",
	"TINYINT",
	"SMALLINT",
	"INT",
	"INTEGER",
	"BIGINT",
	"STRING_NUM",
	"INTEGER_NUM",
	"FLOAT_NUM",
	"DECIMAL_NUM",
	"TRUE_NUM",
	"FALSE_NUM",
	"ID",
	"AT_ID",
	"AT_AT_ID",
	"HEX",
	"INTEGRAL",
	"DECIMAL",
	"HEXNUM",
	"BIT_LITERAL",
	"UTINYINT",
	"USMALLINT",
	"UINT",
	"UBIGINT",
	"REAL",
	"IF",
	"EXISTS",
	"NULL",
	"DEFAULT",
	"TAG",
	"VALUE",
	"DATABASE",
	"TABLE",
	"';'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 290

var yyAct = [...]uint8{
	105, 104, 70, 67, 71, 102, 125, 146, 171, 103,
	63, 74, 29, 16, 38, 19, 17, 163, 25, 31,
	30, 162, 39, 41, 42, 44, 66, 32, 33, 34,
	35, 36, 37, 28, 130, 131, 56, 106, 107, 108,
	64, 109, 110, 50, 107, 108, 43, 109, 110, 197,
	58, 59, 60, 25, 25, 106, 65, 121, 211, 29,
	76, 72, 75, 219, 217, 218, 31, 30, 212, 179,
	122, 100, 173, 111, 32, 33, 34, 35, 36, 37,
	28, 128, 126, 85, 99, 148, 147, 65, 172, 98,
	97, 86, 84, 87, 88, 89, 90, 91, 77, 9,
	10, 57, 46, 12, 11, 48, 45, 13, 136, 24,
	55, 21, 92, 93, 94, 95, 96, 14, 137, 75,
	75, 78, 145, 129, 180, 20, 138, 139, 143, 144,
	69, 18, 182, 52, 181, 160, 127, 65, 161, 165,
	167, 54, 113, 164, 170, 166, 168, 135, 216, 47,
	175, 174, 53, 101, 177, 177, 176, 178, 61, 62,
	142, 189, 141, 183, 184, 185, 186, 187, 188, 190,
	179, 150, 191, 192, 149, 196, 205, 115, 199, 29,
	114, 203, 204, 198, 206, 201, 31, 30, 113, 214,
	135, 210, 113, 209, 32, 33, 34, 35, 36, 37,
	28, 208, 169, 22, 135, 207, 135, 195, 29, 135,
	194, 213, 68, 40, 215, 31, 30, 82, 193, 140,
	220, 135, 134, 32, 33, 34, 35, 36, 37, 28,
	29, 113, 112, 82, 81, 80, 79, 31, 30, 133,
	132, 51, 49, 15, 152, 32, 33, 34, 35, 36,
	37, 28, 153, 154, 155, 156, 157, 158, 152, 1,
	159, 124, 200, 202, 117, 123, 153, 154, 155, 156,
	157, 158, 118, 23, 159, 26, 151, 119, 27, 83,
	120, 73, 116, 8, 7, 6, 5, 4, 3, 2,
}

var yyPact = [...]int16{
	54, -1000, -93, -1000, -1000, -1000, -1000, -1000, -1000, -89,
	84, -90, 74, 166, -91, -1000, -1000, 115, -5, -52,
	-5, 55, 51, 98, -1000, 236, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -5, 235,
	120, 104, -1000, -63, 49, -5, -5, -5, -5, -5,
	-1000, -5, -73, 206, 82, -5, -5, -5, -1000, 46,
	46, -1000, 228, 226, -1000, 19, -5, 146, -42, 206,
	224, -1000, -1000, 168, -1000, 251, 13, -5, 13, -1000,
	-36, -1000, -5, -68, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	234, 233, 214, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 146, 60, -5, -5, -5, 213, 131, -42, -42,
	-24, 31, 29, 162, -1000, -1000, 245, 31, 130, -1000,
	-80, -84, -5, -42, -1000, -42, 206, -1000, -1000, -1000,
	-42, 196, -24, -1000, -1000, -1000, 34, 16, 144, -5,
	-5, 63, 103, -42, -42, -42, -42, -42, -42, -24,
	34, -1000, -42, -42, 210, 202, -1000, 146, 199, -42,
	-1000, -1000, -31, 177, 135, -5, -1000, 231, -1000, -42,
	-42, 170, -24, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 197, -1000, -5, 185,
	164, 183, -4, -1000, 8, -42, -1000, -1000, 181, -1000,
	-1000, -1000, -24, 140, 6, 3, -1000, -1000, -1000, -36,
	-1000,
}

var yyPgo = [...]int16{
	0, 289, 288, 287, 286, 285, 284, 283, 281, 11,
	3, 2, 5, 57, 10, 40, 279, 4, 9, 0,
	1, 278, 8, 275, 273, 109, 7, 60, 265, 263,
	261, 6, 259, 243,
}

var yyR1 = [...]int8{
	0, 32, 33, 33, 1, 1, 1, 1, 1, 1,
	2, 2, 14, 14, 15, 15, 15, 15, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 18, 18, 20, 19, 19, 19,
	19, 17, 17, 23, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 3, 3, 3, 11, 11, 10, 10,
	12, 12, 4, 4, 5, 5, 5, 8, 8, 8,
	9, 9, 9, 9, 9, 9, 6, 6, 24, 24,
	25, 25, 25, 22, 22, 26, 26, 26, 26, 13,
	13, 13, 27, 27, 28, 28, 28, 28, 31, 31,
	31, 31, 31, 31, 31, 31, 31, 31, 30, 29,
	29, 29, 7,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	6, 9, 1, 3, 3, 5, 3, 5, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 5, 6, 8, 1, 3, 3, 5,
	1, 3, 3, 5, 3, 4, 5, 1, 3, 3,
	5, 6, 3, 3, 3, 4, 8, 8, 1, 3,
	4, 6, 1, 0, 2, 0, 5, 6, 6, 0,
	3, 5, 0, 2, 1, 1, 3, 3, 5, 6,
	3, 3, 3, 3, 3, 3, 3, 4, 5, 1,
	3, 5, 3,
}

var yyChk = [...]int16{
	-1000, -32, -1, -2, -3, -4, -5, -6, -7, 45,
	46, 50, 49, 53, 63, -33, 106, 105, 47, 105,
	51, 37, 37, -24, -25, -17, -23, -21, 85, 64,
	72, 71, 79, 80, 81, 82, 83, 84, 105, -17,
	98, -17, -17, 98, -17, 51, 51, 51, 7, 6,
	-17, 6, 13, 48, 37, 6, 99, 52, -17, -17,
	-17, -25, -25, -14, -15, -17, 99, -10, 6, 48,
	-11, -17, -17, -8, -9, -17, -27, 52, -27, 8,
	7, 8, 7, -16, 73, 64, 72, 74, 75, 76,
	77, 78, 93, 94, 95, 96, 97, 71, 70, 65,
	-17, 7, -12, -18, -20, -19, 79, 80, 81, 83,
	84, -10, 8, 7, 12, 9, 31, 13, 21, 26,
	29, -13, 57, -28, -30, -31, -17, -13, -19, -15,
	102, 103, 6, 6, 8, 7, 48, -17, -9, -9,
	6, 31, 29, -18, -18, -20, -26, 55, 56, 12,
	9, 31, 13, 21, 22, 23, 24, 25, 26, 29,
	-26, 8, 101, 101, -14, -12, -18, -10, -12, 6,
	-20, -22, 54, 56, -11, 6, -31, -17, -31, 6,
	61, 31, 29, -18, -18, -18, -18, -18, -18, -20,
	-22, -18, -18, 8, 8, 8, -12, 80, 6, -11,
	31, -12, -29, -19, -20, 6, -20, 8, -11, 8,
	8, 62, 60, -12, 8, -20, 8, 58, 59, 60,
	-19,
}

var yyDef = [...]int8{
	0, -2, 2, 4, 5, 6, 7, 8, 9, 0,
	0, 0, 0, 0, 0, 1, 3, 0, 0, 0,
	0, 0, 0, 0, 78, 82, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 0, 0,
	0, 0, 62, 0, 64, 0, 0, 0, 0, 0,
	112, 0, 0, 0, 0, 0, 0, 0, 65, 92,
	92, 79, 0, 0, 12, 0, 0, 53, 0, 0,
	0, 56, 63, 66, 67, 0, 89, 0, 89, 80,
	0, 10, 0, 0, 18, 19, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
	0, 0, 0, 60, 34, 35, 36, 37, 38, 39,
	40, 54, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 85, 0, 93, 94, 95, 0, 85, 0, 13,
	14, 16, 0, 0, 58, 0, 0, 57, 68, 69,
	0, 0, 0, 72, 73, 74, 83, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	83, 81, 0, 0, 0, 0, 61, 55, 0, 0,
	75, 76, 0, 0, 90, 0, 96, 0, 97, 0,
	0, 0, 0, 100, 101, 102, 103, 104, 105, 106,
	77, 15, 17, 11, 59, 70, 0, 84, 0, 0,
	0, 0, 0, 109, 0, 0, 107, 71, 0, 91,
	98, 108, 0, 0, 86, 110, 99, 87, 88, 0,
	111,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 14, 3, 3, 3, 40, 32, 3,
	6, 8, 37, 35, 7, 36, 3, 38, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 60, 106,
	22, 21, 23, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 61, 3, 62, 42, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 10, 3, 43,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 9, 11, 12, 13, 15, 16,
	17, 18, 19, 20, 24, 25, 26, 27, 28, 29,
	30, 31, 33, 34, 39, 41, 44, 45, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	58, 59, 63, 64, 65, 66, 67, 68, 69, 70,
	71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
	81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
	91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
	101, 102, 103, 104, 105,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:108
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:111
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:112
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:115
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:116
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:117
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:118
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:119
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:120
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 10:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:124
		{
			yyVAL.statement = &CreateStatement{CreateTable: &Table{TableName: yyDollar[3].str, Columns: yyDollar[5].columns}, IfNotExists: false}
			setDDL(yylex, yyVAL.statement)
		}
	case 11:
		yyDollar = yyS[yypt-9 : yypt+1]
//line sql.y:129
		{
			yyVAL.statement = &CreateStatement{CreateTable: &Table{TableName: yyDollar[6].str, Columns: yyDollar[8].columns}, IfNotExists: true}
			setDDL(yylex, yyVAL.statement)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:136
		{
			yyVAL.columns = []*Column{yyDollar[1].column}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:137
		{
			yyVAL.columns = append(yyDollar[1].columns, yyDollar[3].column)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:141
		{
			yyVAL.column = &Column{ColumnName: yyDollar[1].str, Type: yyDollar[2].columnType, Tag: true, Default: ""}
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:145
		{
			yyVAL.column = &Column{ColumnName: yyDollar[1].str, Type: yyDollar[2].columnType, Tag: true, Default: yyDollar[5].str}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:149
		{
			yyVAL.column = &Column{ColumnName: yyDollar[1].str, Type: yyDollar[2].columnType, Tag: false, Default: ""}
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:153
		{
			yyVAL.column = &Column{ColumnName: yyDollar[1].str, Type: yyDollar[2].columnType, Tag: false, Default: yyDollar[5].str}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:158
		{
			yyVAL.columnType = reflect.Bool
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:159
		{
			yyVAL.columnType = reflect.Bool
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:160
		{
			yyVAL.columnType = reflect.Bool
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:161
		{
			yyVAL.columnType = reflect.Int8
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:162
		{
			yyVAL.columnType = reflect.Int16
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:163
		{
			yyVAL.columnType = reflect.Int32
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:164
		{
			yyVAL.columnType = reflect.Int32
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:165
		{
			yyVAL.columnType = reflect.Int64
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:166
		{
			yyVAL.columnType = reflect.Uint8
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:167
		{
			yyVAL.columnType = reflect.Uint16
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:168
		{
			yyVAL.columnType = reflect.Uint32
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:169
		{
			yyVAL.columnType = reflect.Uint64
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:170
		{
			yyVAL.columnType = reflect.Float32
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:171
		{
			yyVAL.columnType = reflect.Float64
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:172
		{
			yyVAL.columnType = reflect.Float32
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:173
		{
			yyVAL.columnType = reflect.String
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:176
		{
			yyVAL.str = yyDollar[1].str
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:177
		{
			yyVAL.str = yyDollar[1].str
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:180
		{
			yyVAL.str = yyDollar[1].str
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:183
		{
			yyVAL.str = yyDollar[1].str
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:184
		{
			yyVAL.str = yyDollar[1].str
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:185
		{
			yyVAL.str = "true"
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:186
		{
			yyVAL.str = "false"
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:189
		{
			yyVAL.str = yyDollar[1].str
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:190
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:193
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 53:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:207
		{
			yyVAL.statement = &InsertStatement{IsStar: true, Columns: nil, TableName: yyDollar[3].str, InsertData: yyDollar[5].tuples}
		}
	case 54:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:208
		{
			yyVAL.statement = &InsertStatement{IsStar: true, Columns: nil, TableName: yyDollar[3].str, InsertData: yyDollar[6].tuples}
		}
	case 55:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:209
		{
			yyVAL.statement = &InsertStatement{IsStar: false, Columns: yyDollar[5].tuple, TableName: yyDollar[3].str, InsertData: yyDollar[8].tuples}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:212
		{
			yyVAL.tuple = []string{yyDollar[1].str}
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:213
		{
			yyVAL.tuple = append(yyDollar[1].tuple, yyDollar[3].str)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:216
		{
			yyVAL.tuples = [][]string{yyDollar[2].tuple}
		}
	case 59:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:217
		{
			yyVAL.tuples = append(yyDollar[1].tuples, yyDollar[4].tuple)
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:220
		{
			yyVAL.tuple = []string{yyDollar[1].str}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:221
		{
			yyVAL.tuple = append(yyDollar[1].tuple, yyDollar[3].str)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:224
		{
			yyVAL.statement = &DropStatement{TableName: yyDollar[3].str, IfExists: false}
		}
	case 63:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:225
		{
			yyVAL.statement = &DropStatement{TableName: yyDollar[5].str, IfExists: true}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:228
		{
			yyVAL.statement = &DeleteStatement{TableName: yyDollar[3].str, IsStar: true, Filters: nil, HasWhere: false}
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:229
		{
			yyVAL.statement = &DeleteStatement{TableName: yyDollar[4].str, IsStar: true, Filters: nil, HasWhere: false}
		}
	case 66:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:230
		{
			yyVAL.statement = &DeleteStatement{TableName: yyDollar[3].str, IsStar: false, Filters: yyDollar[5].deleteFilters, HasWhere: true}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:233
		{
			yyVAL.deleteFilters = &DeleteFilter{AndTagFilters: []*TagFilter{yyDollar[1].tagFilter}, OrTagFilters: nil}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:234
		{
			yyVAL.deleteFilters = andJoinTagFilters(yyDollar[1].deleteFilters, yyDollar[3].tagFilter)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:235
		{
			yyVAL.deleteFilters = orJoinTagFilters(yyDollar[1].deleteFilters, yyDollar[3].tagFilter)
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:238
		{
			yyVAL.tagFilter = &TagFilter{Key: yyDollar[1].str, Value: strings.Join(yyDollar[4].tuple, "|"), IsNegative: false, IsRegexp: true}
		}
	case 71:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:239
		{
			yyVAL.tagFilter = &TagFilter{Key: yyDollar[1].str, Value: strings.Join(yyDollar[5].tuple, "|"), IsNegative: true, IsRegexp: true}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:240
		{
			yyVAL.tagFilter = &TagFilter{Key: yyDollar[1].str, Value: yyDollar[3].str, IsNegative: false, IsRegexp: false}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:241
		{
			yyVAL.tagFilter = &TagFilter{Key: yyDollar[1].str, Value: yyDollar[3].str, IsNegative: true, IsRegexp: false}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:242
		{
			yyVAL.tagFilter = &TagFilter{Key: yyDollar[1].str, Value: yyDollar[3].str, IsNegative: false, IsRegexp: true}
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:243
		{
			yyVAL.tagFilter = &TagFilter{Key: yyDollar[1].str, Value: yyDollar[4].str, IsNegative: true, IsRegexp: true}
		}
	case 76:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:247
		{
			yyVAL.statement = &SelectStatement{
				TableName:   yyDollar[4].str,
				IsStar:      true,
				Columns:     nil,
				WhereFilter: yyDollar[5].whereFilters,
				GroupBy:     yyDollar[6].tuple,
				OrderBy:     yyDollar[7].orderBy,
				Limit:       yyDollar[8].str,
			}
		}
	case 77:
		yyDollar = yyS[yypt-8 : yypt+1]
//line sql.y:259
		{
			yyVAL.statement = &SelectStatement{
				TableName:   yyDollar[4].str,
				IsStar:      true,
				Columns:     yyDollar[2].functions,
				WhereFilter: yyDollar[5].whereFilters,
				GroupBy:     yyDollar[6].tuple,
				OrderBy:     yyDollar[7].orderBy,
				Limit:       yyDollar[8].str,
			}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:272
		{
			yyVAL.functions = [][]*Function{yyDollar[1].function}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:273
		{
			yyVAL.functions = append(yyDollar[1].functions, yyDollar[3].function)
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:277
		{
			yyVAL.function = append(yyDollar[3].function, &Function{FuncName: yyDollar[1].str, Args: []string{""}})
		}
	case 81:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:279
		{
			yyVAL.function = append(yyDollar[3].function, &Function{FuncName: yyDollar[1].str, Args: []string{"", yyDollar[5].str}})
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:280
		{
			yyVAL.function = []*Function{{FuncName: "", Args: []string{yyDollar[1].str}}}
		}
	case 83:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:283
		{
			yyVAL.str = ""
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:284
		{
			yyVAL.str = yyDollar[2].str
		}
	case 85:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:287
		{
			yyVAL.orderBy = nil
		}
	case 86:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:288
		{
			yyVAL.orderBy = &OrderBy{SortingKey: yyDollar[4].tuple, IsAsc: true}
		}
	case 87:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:289
		{
			yyVAL.orderBy = &OrderBy{SortingKey: yyDollar[4].tuple, IsAsc: false}
		}
	case 88:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:290
		{
			yyVAL.orderBy = &OrderBy{SortingKey: yyDollar[4].tuple, IsAsc: true}
		}
	case 89:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:293
		{
			yyVAL.tuple = nil
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:294
		{
			yyVAL.tuple = yyDollar[3].tuple
		}
	case 91:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:295
		{
			yyVAL.tuple = yyDollar[4].tuple
		}
	case 92:
		yyDollar = yyS[yypt-0 : yypt+1]
//line sql.y:298
		{
			yyVAL.whereFilters = nil
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line sql.y:299
		{
			yyVAL.whereFilters = yyDollar[2].whereFilters
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:302
		{
			yyVAL.whereFilters = &MultiFilters{TimeFilter: yyDollar[1].timeFilter, AndFilters: nil}
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:303
		{
			yyVAL.whereFilters = &MultiFilters{TimeFilter: nil, AndFilters: []*OtherFilter{yyDollar[1].otherFilter}}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:304
		{
			yyVAL.whereFilters = andJoinMultiFilters(yyDollar[1].whereFilters, yyDollar[3].otherFilter)
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:305
		{
			yyVAL.whereFilters = orJoinMultiFilters(yyDollar[1].whereFilters, yyDollar[3].otherFilter)
		}
	case 98:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:308
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "IN", Args: strings.Join(yyDollar[4].tuple, "|")}
		}
	case 99:
		yyDollar = yyS[yypt-6 : yypt+1]
//line sql.y:309
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "NOTIN", Args: strings.Join(yyDollar[5].tuple, "|")}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:310
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "=", Args: yyDollar[3].str}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:311
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "<", Args: yyDollar[3].str}
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:312
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: ">", Args: yyDollar[3].str}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:313
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "LE", Args: yyDollar[3].str}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:314
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "GE", Args: yyDollar[3].str}
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:315
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "NE", Args: yyDollar[3].str}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:316
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "LIKE", Args: yyDollar[3].str}
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
//line sql.y:317
		{
			yyVAL.otherFilter = &OtherFilter{Key: yyDollar[1].str, Op: "NOTLIKE", Args: yyDollar[4].str}
		}
	case 108:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:321
		{
			if strings.ToLower(yyDollar[1].str) == "timestamp" {
				yyVAL.timeFilter = yyDollar[4].timeFilter
			} else {
				yyVAL.timeFilter = nil
			}
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line sql.y:330
		{
			yyVAL.timeFilter = &TimeFilter{Start: "", End: "", Step: yyDollar[1].str}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:331
		{
			yyVAL.timeFilter = &TimeFilter{Start: yyDollar[1].str, End: yyDollar[3].str, Step: ""}
		}
	case 111:
		yyDollar = yyS[yypt-5 : yypt+1]
//line sql.y:332
		{
			yyVAL.timeFilter = &TimeFilter{Start: yyDollar[1].str, End: yyDollar[3].str, Step: yyDollar[5].str}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line sql.y:335
		{
			yyVAL.statement = &DescribeStatement{TableName: yyDollar[3].str}
		}
	}
	goto yystack /* stack new state and value */
}
